/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.ConectorDB;
import Clases.LimpiadorDeEntrada;
import Clases.Provincia;
import Clases.ProvinciaCiudad;
import Clases.RolDePagos;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Fabricio Mero
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    // Objetos y variables globales.
    ProvinciaCiudad lugares = new ProvinciaCiudad();
    LimpiadorDeEntrada limpiador = new LimpiadorDeEntrada();
    RolDePagos rdp = new RolDePagos();

    int tipoIdentificacion = 0; 

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null); //Centrar pantalla
        this.lugares.cargarComboProvincias(cbo_Provincia);
        radIndividual.setSelected(true);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        LayeredPane = new javax.swing.JLayeredPane();
        jPanel4 = new javax.swing.JPanel();
        txt_sueldo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtHorasExtras50 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_DecimoTercero = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_DecimoCuarto = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_FondosReserva = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_TotalIngresos = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_Iess = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_ImpuestoRenta = new javax.swing.JTextField();
        txt_ValorRecibir = new javax.swing.JTextField();
        txt_TotalDescuentos = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtCedulaBusqueda = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        btnCargarDatos = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        txtHorasExtras100 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtComisiones = new javax.swing.JTextField();
        txtAnticipos = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtMultas = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnCalcularRol = new javax.swing.JButton();
        txt_nombreTrabajador = new javax.swing.JLabel();
        btn_registrarRol = new javax.swing.JButton();
        pnlReportes = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        cmbMesReporte = new javax.swing.JComboBox<>();
        radIndividual = new javax.swing.JRadioButton();
        radTodos = new javax.swing.JRadioButton();
        txbCedula = new javax.swing.JTextField();
        txtIngreseIdent = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaReporte = new javax.swing.JTable();
        pnlRegistroTrabajador = new javax.swing.JPanel();
        cbo_Provincia = new javax.swing.JComboBox<>();
        cbo_Ciudad = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_Direccion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_Telefono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbo_TipIden = new javax.swing.JComboBox<>();
        txt_Identificacion = new javax.swing.JTextField();
        txt_Apellidos = new javax.swing.JTextField();
        txt_Nombres = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_AgregarTrabajador = new javax.swing.JButton();
        txt_Sueldo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        radDecimoTercero = new javax.swing.JRadioButton();
        radDecimoCuarto = new javax.swing.JRadioButton();
        radFondosReserva = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lbl_RegistroTrabajdores = new javax.swing.JLabel();
        btn_RegistroSueldos = new org.edisoncor.gui.button.ButtonTransluceIcon();
        btn_RegistroTrabajadores = new org.edisoncor.gui.button.ButtonTransluceIcon();
        lbl_RegistroSueldos = new javax.swing.JLabel();
        btn_GenerarRol = new org.edisoncor.gui.button.ButtonTransluceIcon();
        lbl_GenerarRol = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LayeredPane.setLayout(new java.awt.CardLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel4.setPreferredSize(new java.awt.Dimension(640, 450));

        txt_sueldo.setEditable(false);
        txt_sueldo.setToolTipText("Campo no editable");

        jLabel11.setText("Décimo tercero");

        txtHorasExtras50.setToolTipText("Ingrese número de horas con valor de 50% del sueldo por hora");
        txtHorasExtras50.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHorasExtras50KeyTyped(evt);
            }
        });

        jLabel12.setText("Décimo cuarto");

        txt_DecimoTercero.setEditable(false);
        txt_DecimoTercero.setToolTipText("Campo no editable");

        jLabel13.setText("Fondos de reserva");

        txt_DecimoCuarto.setEditable(false);
        txt_DecimoCuarto.setToolTipText("Campo no editable");

        jLabel14.setText("Total ingresos");

        txt_FondosReserva.setEditable(false);
        txt_FondosReserva.setToolTipText("Campo no editable");

        jLabel16.setText("Iess");

        txt_TotalIngresos.setEditable(false);
        txt_TotalIngresos.setToolTipText("Campo no editable");

        jLabel17.setText("Impuesto a la Renta");

        txt_Iess.setEditable(false);
        txt_Iess.setToolTipText("Campo no editable");

        jLabel18.setText("Total descuentos");

        txt_ImpuestoRenta.setEditable(false);
        txt_ImpuestoRenta.setToolTipText("Campo no editable");

        txt_ValorRecibir.setEditable(false);
        txt_ValorRecibir.setToolTipText("Campo no editable");

        txt_TotalDescuentos.setEditable(false);
        txt_TotalDescuentos.setToolTipText("Campo no editable");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel19.setText("Valor a recibir");

        jLabel20.setText("Sueldo");

        jLabel21.setText("Horas extras 50%");

        jLabel22.setText("Trabajador/a: ");

        txtCedulaBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaBusquedaKeyTyped(evt);
            }
        });

        jLabel24.setText("Cedula");

        btnCargarDatos.setText("Cargar datos");
        btnCargarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarDatosActionPerformed(evt);
            }
        });

        jLabel25.setText("Horas extras 100%");
        jLabel25.setToolTipText("Ingrese número de horas con valor de 100% del sueldo por hora");

        txtHorasExtras100.setToolTipText("Ingrese número de horas con valor de 100% del sueldo por hora");
        txtHorasExtras100.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHorasExtras100KeyTyped(evt);
            }
        });

        jLabel27.setText("Comisiones");

        txtComisiones.setToolTipText("Ingrese total de comisiones ganadas por el trabajador");
        txtComisiones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtComisionesKeyTyped(evt);
            }
        });

        txtAnticipos.setToolTipText("Ingrese total de anticipos de sueldo que ha hecho el trabajador");
        txtAnticipos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAnticiposKeyTyped(evt);
            }
        });

        jLabel28.setText("Anticipos");

        txtMultas.setToolTipText("Ingrese total de multas del trabajador");
        txtMultas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMultasKeyTyped(evt);
            }
        });

        jLabel29.setText("Multas");

        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("Cancela la operación y linpia todos los campos");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnCalcularRol.setText("Calcular");
        btnCalcularRol.setToolTipText("Calcule los valores de todas los campos ");
        btnCalcularRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularRolActionPerformed(evt);
            }
        });

        btn_registrarRol.setText("Registrar rol ");
        btn_registrarRol.setToolTipText("Almacena el registro en la base de datos");
        btn_registrarRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarRolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCedulaBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCargarDatos))
                    .addComponent(btnCalcularRol, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_registrarRol)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar)
                        .addGap(261, 261, 261))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(txt_nombreTrabajador)
                        .addGap(189, 189, 189))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(196, 196, 196))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_FondosReserva)
                            .addComponent(txt_DecimoCuarto)
                            .addComponent(txt_DecimoTercero, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel27)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtHorasExtras100, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtHorasExtras50)
                            .addComponent(txt_sueldo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtComisiones, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_TotalIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_TotalDescuentos, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_ValorRecibir, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_Iess)
                                    .addComponent(txt_ImpuestoRenta)
                                    .addComponent(txtMultas)
                                    .addComponent(txtAnticipos, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtCedulaBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCargarDatos)
                    .addComponent(txt_nombreTrabajador))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_Iess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16))
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_ImpuestoRenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAnticipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_TotalIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_TotalDescuentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txt_ValorRecibir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHorasExtras50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHorasExtras100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtComisiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_DecimoTercero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_DecimoCuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_FondosReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcularRol)
                    .addComponent(btnCancelar)
                    .addComponent(btn_registrarRol))
                .addGap(19, 19, 19))
        );

        LayeredPane.add(jPanel4, "card3");

        pnlReportes.setPreferredSize(new java.awt.Dimension(532, 440));

        jLabel26.setText("Mes");

        cmbMesReporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        radIndividual.setText("Individual");
        radIndividual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radIndividualActionPerformed(evt);
            }
        });

        radTodos.setText("Todos");
        radTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radTodosActionPerformed(evt);
            }
        });

        txbCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txbCedulaKeyTyped(evt);
            }
        });

        txtIngreseIdent.setText("Ingrese identificacion");

        jButton2.setText("Consultar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tablaReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Trabajador", "Sueldo", "Iess", "Horas\n extra50%", "Horas extra 100%", "DecimoTercero", "DecimoCuarto", "Fondos de reserva", "Impuesto a la renta", "Comisiones", "Multas", "Anticipos", "Total ingresos", "Total descuentos", "Valor a recibir"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaReporte.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaReporte);

        javax.swing.GroupLayout pnlReportesLayout = new javax.swing.GroupLayout(pnlReportes);
        pnlReportes.setLayout(pnlReportesLayout);
        pnlReportesLayout.setHorizontalGroup(
            pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReportesLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(txtIngreseIdent)
                .addGap(86, 86, 86)
                .addComponent(jLabel26))
            .addGroup(pnlReportesLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(radIndividual)
                .addGap(8, 8, 8)
                .addComponent(txbCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(cmbMesReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton2))
            .addGroup(pnlReportesLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(radTodos))
            .addGroup(pnlReportesLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlReportesLayout.setVerticalGroup(
            pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReportesLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIngreseIdent)
                    .addComponent(jLabel26))
                .addGap(7, 7, 7)
                .addGroup(pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radIndividual)
                    .addComponent(jButton2)
                    .addGroup(pnlReportesLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txbCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbMesReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(3, 3, 3)
                .addComponent(radTodos)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        LayeredPane.add(pnlReportes, "card4");

        pnlRegistroTrabajador.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        pnlRegistroTrabajador.setPreferredSize(new java.awt.Dimension(640, 450));

        cbo_Provincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE" }));
        cbo_Provincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_ProvinciaActionPerformed(evt);
            }
        });

        cbo_Ciudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE" }));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Provincia");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Ciudad");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Dirección");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Teléfono");

        cbo_TipIden.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Cédula", "Pasaporte" }));
        cbo_TipIden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_TipIdenActionPerformed(evt);
            }
        });

        txt_Identificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_IdentificacionKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Tipo de identificación");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Identificación");

        jLabel3.setText("Apellidos");

        jLabel4.setText("Nombres");

        btn_AgregarTrabajador.setText("Registrar Trabajador");
        btn_AgregarTrabajador.setMaximumSize(new java.awt.Dimension(85, 25));
        btn_AgregarTrabajador.setMinimumSize(new java.awt.Dimension(90, 25));
        btn_AgregarTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarTrabajadorActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Sueldo");

        radDecimoTercero.setText("Décimo tercer sueldo");

        radDecimoCuarto.setText("Décimo cuarto sueldo");

        radFondosReserva.setText("Fondos de reserva");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setText("Mensualizar");

        jLabel15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 102, 0));
        jLabel15.setText("Registro de Trabajadores");

        javax.swing.GroupLayout pnlRegistroTrabajadorLayout = new javax.swing.GroupLayout(pnlRegistroTrabajador);
        pnlRegistroTrabajador.setLayout(pnlRegistroTrabajadorLayout);
        pnlRegistroTrabajadorLayout.setHorizontalGroup(
            pnlRegistroTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroTrabajadorLayout.createSequentialGroup()
                .addGroup(pnlRegistroTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistroTrabajadorLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(pnlRegistroTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlRegistroTrabajadorLayout.createSequentialGroup()
                                .addComponent(cbo_TipIden, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_Identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlRegistroTrabajadorLayout.createSequentialGroup()
                                .addComponent(cbo_Provincia, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(cbo_Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlRegistroTrabajadorLayout.createSequentialGroup()
                                .addComponent(txt_Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(txt_Nombres, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlRegistroTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlRegistroTrabajadorLayout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addGroup(pnlRegistroTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(radDecimoTercero)
                                        .addComponent(radDecimoCuarto)
                                        .addComponent(jLabel10)
                                        .addGroup(pnlRegistroTrabajadorLayout.createSequentialGroup()
                                            .addComponent(radFondosReserva)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn_AgregarTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlRegistroTrabajadorLayout.createSequentialGroup()
                                    .addComponent(txt_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(12, 12, 12)
                                    .addComponent(txt_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(txt_Sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlRegistroTrabajadorLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(pnlRegistroTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlRegistroTrabajadorLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(228, 228, 228)
                                        .addComponent(jLabel9)
                                        .addGap(102, 102, 102)
                                        .addComponent(jLabel8))
                                    .addGroup(pnlRegistroTrabajadorLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(230, 230, 230)
                                        .addComponent(jLabel6))
                                    .addGroup(pnlRegistroTrabajadorLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(229, 229, 229)
                                        .addComponent(jLabel4))
                                    .addGroup(pnlRegistroTrabajadorLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(23, 23, 23)
                                        .addComponent(jLabel2))))))
                    .addGroup(pnlRegistroTrabajadorLayout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jLabel15)))
                .addGap(0, 0, 0))
        );
        pnlRegistroTrabajadorLayout.setVerticalGroup(
            pnlRegistroTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroTrabajadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(30, 30, 30)
                .addGroup(pnlRegistroTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(0, 0, 0)
                .addGroup(pnlRegistroTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbo_TipIden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(pnlRegistroTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(0, 0, 0)
                .addGroup(pnlRegistroTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegistroTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(0, 0, 0)
                .addGroup(pnlRegistroTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbo_Provincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlRegistroTrabajadorLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cbo_Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(pnlRegistroTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addGap(0, 0, 0)
                .addGroup(pnlRegistroTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jLabel10)
                .addGap(3, 3, 3)
                .addComponent(radDecimoTercero)
                .addGap(0, 0, 0)
                .addComponent(radDecimoCuarto)
                .addGap(0, 0, 0)
                .addGroup(pnlRegistroTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radFondosReserva)
                    .addComponent(btn_AgregarTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        LayeredPane.add(pnlRegistroTrabajador, "card2");

        lbl_RegistroTrabajdores.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbl_RegistroTrabajdores.setText("Registro de Trabajadores");

        btn_RegistroSueldos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/sueldos.png"))); // NOI18N
        btn_RegistroSueldos.setText("buttonTransluceIcon1");
        btn_RegistroSueldos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegistroSueldosActionPerformed(evt);
            }
        });

        btn_RegistroTrabajadores.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_RegistroTrabajadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/constructor.png"))); // NOI18N
        btn_RegistroTrabajadores.setText("buttonTransluceIcon2");
        btn_RegistroTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegistroTrabajadoresActionPerformed(evt);
            }
        });

        lbl_RegistroSueldos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbl_RegistroSueldos.setText("Registro de Sueldos");

        btn_GenerarRol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/reporte.png"))); // NOI18N
        btn_GenerarRol.setText("buttonTransluceIcon1");
        btn_GenerarRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GenerarRolActionPerformed(evt);
            }
        });

        lbl_GenerarRol.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbl_GenerarRol.setText("Generar Rol de Pagos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btn_RegistroTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_RegistroTrabajdores)
                    .addComponent(btn_RegistroSueldos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_RegistroSueldos)
                    .addComponent(btn_GenerarRol, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_GenerarRol))
                .addGap(26, 26, 26)
                .addComponent(LayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_RegistroTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(lbl_RegistroTrabajdores)
                        .addGap(35, 35, 35)
                        .addComponent(btn_RegistroSueldos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_RegistroSueldos)
                        .addGap(30, 30, 30)
                        .addComponent(btn_GenerarRol, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_GenerarRol, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_RegistroSueldosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegistroSueldosActionPerformed
        LayeredPane.removeAll();
        LayeredPane.add(jPanel4);
        LayeredPane.repaint();
        LayeredPane.revalidate();
    }//GEN-LAST:event_btn_RegistroSueldosActionPerformed

    private void btn_RegistroTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegistroTrabajadoresActionPerformed
        LayeredPane.removeAll();
        LayeredPane.add(pnlRegistroTrabajador);
        LayeredPane.repaint();
        LayeredPane.revalidate();
    }//GEN-LAST:event_btn_RegistroTrabajadoresActionPerformed

    private void btn_AgregarTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarTrabajadorActionPerformed
        // Argumentos para insertar en la DB.

        String tipoIdentificacion = String.valueOf(cbo_TipIden.getSelectedIndex());;
        String identificacion = txt_Identificacion.getText();
        String apellidos = txt_Apellidos.getText();
        String nombres = txt_Nombres.getText();
        String ciudad = String.valueOf(cbo_Ciudad.getSelectedIndex());
        String telefono = txt_Telefono.getText();
        String fechaRegistro = "";
        String direccion = txt_Direccion.getText();
        String sueldo = txt_Sueldo.getText();
        String decimoTercero = radDecimoTercero.isSelected()? "1":"0"; // True: Mensualizado. False: No mensualizado.
        String decimoCuarto = radDecimoCuarto.isSelected()? "1":"0";
        String fondoReserva = radFondosReserva.isSelected()? "1":"0";
        
        // Para tratar con la DB.
        ConectorDB con = new ConectorDB();

        // Verificamos que no falte ningun campo.
        if(
            identificacion.isEmpty() ||
            apellidos.isEmpty() ||
            nombres.isEmpty() ||
            direccion.isEmpty() ||
            telefono.isEmpty() ||
            sueldo.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Llene todos los campos");
            return;
        }

        // Depuramos valores de entrada.

        // Cedula.
        if (identificacion.length() != 10 ||
            !limpiador.ValidarCedula(identificacion))
        {
            JOptionPane.showMessageDialog(this, "Cédula no válida");
        }
        
        ResultSet cedulaRepetida;
        cedulaRepetida = con.consultar("SELECT Identificacion FROM Trabajador WHERE Identificacion='"+ identificacion +"'");
        
        try{
            if(cedulaRepetida.next()){
                JOptionPane.showMessageDialog(this, "Esa cédula ya ha sido registrada\ny no puede volver a registrarse");
                return;
            }
        }
        catch(SQLException ex){
            
        }
        
        // Apellidos.
        if (!limpiador.soloLetras(apellidos) || apellidos.length() > 30){
            JOptionPane.showMessageDialog(this, "Ingrese hasta 30 letras en el campo \"Apellidos\"");
            return;
        }

        // Nombres.
        else if (!limpiador.soloLetras(nombres) || nombres.length() > 30){
            JOptionPane.showMessageDialog(this, "Ingrese hasta 30 letras en el campo \"Nombres\"");
            return;
        }

        // Tipo de cedula.
        else if (cbo_TipIden.getSelectedIndex() == 0 ){
            JOptionPane.showMessageDialog(this, "Seleccione un tipo de identificación");
            return;
        }

        // Provincia.
        else if (cbo_Provincia.getSelectedIndex() == 0 )
        {
            JOptionPane.showMessageDialog(this, "Seleccione una provincia");
            return;
        }

        // Ciudad.
        else if(cbo_Ciudad.getSelectedIndex() == 0 ){
            JOptionPane.showMessageDialog(this, "Seleccione una ciudad");
            return;
        }

        // Direccion (hasta 100 caracteres).
        else if (txt_Direccion.getText().length() > 100){
            JOptionPane.showMessageDialog(this, "Ingrese una dirección de hasta 100 caracteres.");
            return;
        }

        // Telefono (entre 6 y 10 caracteres).
        else if (!limpiador.soloEnteros(telefono) | telefono.length() < 6 |
            telefono.length() > 10)

        // Sueldo. 398 (VALOR QUEMADO!!! CONSIDERAR HACER UNA TABLA DE CONFIGURACIONES EN LA DB DONDE SE PUEDA EDITAR)
        if (!limpiador.soloDecimales(sueldo) | Double.parseDouble(sueldo) < 398 |
            Double.parseDouble(sueldo) > 100000){
            JOptionPane.showMessageDialog(this, "Ingrese valores positivos desde 398 hasta 100000 ");
        }

        // Obtenemos fecha y hora de registro.
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        LocalDateTime fechaActual = LocalDateTime.now();
        fechaRegistro = dtf.format(fechaActual);

        // Preparamos lista de argumentos.
        String[] args  = {tipoIdentificacion, identificacion, apellidos, nombres,
            ciudad, telefono, fechaRegistro, sueldo, direccion};
//.toUppercase
        

        // Query de insercion.
        String query = "INSERT INTO Trabajador (TipoIdentificacion, Identificacion, Apellidos, Nombres, "
        + "Ciudad, Telefono, FechaRegistro, Sueldo, Direccion,DecimoTerceroMensualiz,DecimoCuartoMensualiz,"
        + " FondosReservaMensualiz,MesesEnEmpresa,Estado) VALUES ('" + tipoIdentificacion + "','" +
        identificacion + "','" + apellidos + "','" + nombres + "','" + ciudad +
        "','" + telefono + "','" + fechaRegistro + "'," + sueldo + ",'" + direccion + "','" + decimoTercero + "','" 
        + decimoCuarto + "','" + fondoReserva + "',0,'A')";
        
        if (con.modificar(query)){
            JOptionPane.showMessageDialog(this, "Registro exitoso");
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Hubo un error inesperado. Reinténtelo después, por favor");
        }
    }//GEN-LAST:event_btn_AgregarTrabajadorActionPerformed

    private void txt_IdentificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_IdentificacionKeyTyped
        limpiador.limitarLargo(evt, txt_Identificacion, 10);
    }//GEN-LAST:event_txt_IdentificacionKeyTyped

    private void cbo_TipIdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_TipIdenActionPerformed
        // Asignamos a variable global el indice seleccionado.
        this.tipoIdentificacion = this.cbo_TipIden.getSelectedIndex();
    }//GEN-LAST:event_cbo_TipIdenActionPerformed

    private void cbo_ProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_ProvinciaActionPerformed
        // TODO add your handling code here:
        String provSelecc = String.valueOf(this.cbo_Provincia.getSelectedItem());

        lugares.cargarComboCiudades(cbo_Ciudad, provSelecc);
    }//GEN-LAST:event_cbo_ProvinciaActionPerformed

    private void btnCargarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarDatosActionPerformed
        if(!limpiador.ValidarCedula(this.txtCedulaBusqueda.getText())){
            JOptionPane.showMessageDialog(this, "Cédula no válida");
            this.txtCedulaBusqueda.setText("");
            return;
        }
        
        String cedula = this.txtCedulaBusqueda.getText();
        ConectorDB con = new ConectorDB();
        
        // Asignamos cedula a objeto rol de pagos.
        rdp.definirIndentificacion(cedula);
        
        // Consultamos sueldo y nombre en la DB.
        String query = "SELECT sueldo, Nombres + ' ' + Apellidos as nombre from Trabajador where Identificacion = '" + cedula + "'";
        
        ResultSet rs = null;

        rs = con.consultar(query);

        if (rs == null){
            System.out.println("error al consultar nombre y sueldo.");
        }

        try{
            while(rs.next()){
                this.txt_nombreTrabajador.setText(rs.getString("nombre"));
                this.txt_sueldo.setText(String.valueOf(rs.getDouble("sueldo")));
            }
        }
        catch( SQLException ex)
        {
            System.out.println("error en btnCargarDatos");
        }
        
        this.txt_DecimoTercero.setText("");
        this.txt_DecimoCuarto.setText("");
        this.txt_FondosReserva.setText("");
        this.txt_Iess.setText("");
        this.txt_ImpuestoRenta.setText("");
        this.txt_TotalIngresos.setText("");
        this.txt_TotalDescuentos.setText("");
        this.txt_ValorRecibir.setText("");

        

    }//GEN-LAST:event_btnCargarDatosActionPerformed

    private void radIndividualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radIndividualActionPerformed
        radTodos.setSelected(false);
        txtIngreseIdent.setVisible(true);
        txtIngreseIdent.setText("");
        txbCedula.setVisible(true);
        txtIngreseIdent.setVisible(true);
        
    }//GEN-LAST:event_radIndividualActionPerformed

    private void radTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radTodosActionPerformed
       radIndividual.setSelected(false);
       txtIngreseIdent.setVisible(false);
        txbCedula.setVisible(false);
        
    }//GEN-LAST:event_radTodosActionPerformed

    private void btn_GenerarRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GenerarRolActionPerformed
        // TODO add your handling code here:
        ReporteRol repRol = new ReporteRol();
        
        repRol.setVisible(true);
        
    }//GEN-LAST:event_btn_GenerarRolActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        // Verificamos input.
        if (txbCedula.getText().length() != 10 || !limpiador.ValidarCedula(txbCedula.getText())){
            JOptionPane.showMessageDialog(this, "Número de cédula incorrecta");
            return;
        }
        
        // Limpiamos la tabla.
        DefaultTableModel dtm = (DefaultTableModel) tablaReporte.getModel();
        dtm.setRowCount(0);
        
        int mes = cmbMesReporte.getSelectedIndex(); 
        int nFilas;
        
        if (mes == 0){
            JOptionPane.showMessageDialog(this, "Seleccione un mes");
            return;
        }
        
        if (radTodos.isSelected()){
            // Para tratar con la DB.
            ConectorDB con = new ConectorDB();
            
            nFilas = 0;
            
            //String query = "SELECT * FROM RolDePagosMensual where ";
            String query = "SELECT rdp.*, t.Nombres + ' ' + t.Apellidos as nombre FROM RolDePagosMensual rdp, Trabajador t"
                    + " where t.Identificacion = rdp.cedula and " + "Month(rdp.Mes) = " + mes;
            ResultSet rs = null;
            
            rs = con.consultar(query);
            
            if (rs == null){
                System.out.println("Error al cargar de tabla RodDePagos todos");
                return;
            }

            try{
                while(rs.next()){
                    nFilas ++;
                    DefaultTableModel model = (DefaultTableModel) tablaReporte.getModel();
                    model.addRow(new Object[]{rs.getString("nombre"), rs.getDouble("Sueldo"),rs.getDouble("Iess"),
                    rs.getDouble("valorHorasExtra50"), rs.getDouble("valorHorasExtra100"), rs.getDouble("DecimoTercero"),
                    rs.getDouble("DecimoCuarto"),rs.getDouble("valorHorasExtra50"), rs.getDouble("FondosReserva"),
                    rs.getDouble("ImpuestoRenta"), rs.getDouble("Comisiones"), rs.getDouble("Multas"), rs.getDouble("Anticipos"),
                    rs.getDouble("TotalIngresos"), rs.getDouble("TotalDescuento"), rs.getDouble("ValorRecibir")});
                }
            }
            catch( SQLException ex)
            {
                System.out.println("error en ejecutarConsulta");
                return;
            }
            
            if (nFilas == 0){
                JOptionPane.showMessageDialog(this, "No existen registros");
            }
        }
        else if (radIndividual.isSelected()){
            // Para tratar con la DB.
            ConectorDB con = new ConectorDB();
            
            nFilas = 0;
            
            String query = "SELECT rdp.*, t.Nombres + ' ' + t.Apellidos as nombre FROM RolDePagosMensual rdp, Trabajador t"
                    + " where rdp.cedula= '" + this.txbCedula.getText() + "' and t.Identificacion = '" + this.txbCedula.getText() + "' and "
                    + "Month(rdp.Mes) = " + mes; 
            
            ResultSet rs = null;
            
            rs = con.consultar(query);
            
            if (rs == null){
                System.out.println("error al carga de tabla RodDePagos individual");
                return;
            }

            try{
                if(rs.next()){
                    nFilas ++;
                    //JRResultSetDataSource resultsetdatasource = new JRResultSetDataSource(rs);
                    //JasperFillManager.fillReport(in, parameterMap, new JRResultSetDataSource(rs));
                    DefaultTableModel model = (DefaultTableModel) tablaReporte.getModel();
                    model.addRow(new Object[]{rs.getString("nombre"), rs.getDouble("Sueldo"),rs.getDouble("Iess"),
                    rs.getDouble("valorHorasExtra50"), rs.getDouble("valorHorasExtra100"), rs.getDouble("DecimoTercero"),
                    rs.getDouble("DecimoCuarto"),rs.getDouble("valorHorasExtra50"), rs.getDouble("FondosReserva"),
                    rs.getDouble("ImpuestoRenta"), rs.getDouble("Comisiones"), rs.getDouble("Multas"), rs.getDouble("Anticipos"),
                    rs.getDouble("TotalIngresos"), rs.getDouble("TotalDescuento"), rs.getDouble("ValorRecibir")});
                }
            }
            catch( SQLException ex)
            {
                System.out.println("error en ejecutarConsulta");
                return;
            }
            
            if (nFilas == 0){
                JOptionPane.showMessageDialog(this, "No existen registros");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.txtCedulaBusqueda.setText("");
        this.txt_nombreTrabajador.setText("");
        this.txt_sueldo.setText("");
        this.txt_DecimoTercero.setText("");
        this.txt_DecimoCuarto.setText("");
        this.txtHorasExtras50.setText("");
        this.txtHorasExtras100.setText("");
        this.txtComisiones.setText("");
        this.txtAnticipos.setText("");
        this.txtMultas.setText("");
        this.txt_FondosReserva.setText("");
        this.txt_Iess.setText("");
        this.txt_ImpuestoRenta.setText("");
        this.txt_TotalIngresos.setText("");
        this.txt_TotalDescuentos.setText("");
        this.txt_ValorRecibir.setText("");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btn_registrarRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarRolActionPerformed
        // Si se quiere registrar un rol ya registrado.
        if(rdp.verificarRepetidos()){
            JOptionPane.showMessageDialog(this, "El rol de pagos de esta persona ya ha sido registrado para el presente mes");
            return;
        }
        
        // se guarda el rol de pagos en la base de datos.    
        this.rdp.almacenarDB();
    }//GEN-LAST:event_btn_registrarRolActionPerformed

    private void btnCalcularRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularRolActionPerformed
        // Calcula rol de pagos para que usuario lo verifique y despues lo registre oficialmente en la DB.
        
        // Si usuario ingresa valores invalidos en campos comision, horas extra,etc.
        if(!rdp.cargarValoresMensuales(txtHorasExtras50.getText(), txtHorasExtras100.getText(), 
                txtMultas.getText(), txtAnticipos.getText(), txtComisiones.getText()))
        {
            JOptionPane.showMessageDialog(this, "Datos ingresados no son válidos");
            return;
        }
        
        rdp.calcularRolPagos();
        
        // mostramos valores.
        this.txt_sueldo.setText(String.format("%.2f",rdp.sueldo));
        this.txt_Iess.setText(String.format("%.2f",rdp.iess));
        this.txt_ImpuestoRenta.setText(String.format("%.2f",rdp.impuestoRenta));
        this.txt_FondosReserva.setText(String.format("%.2f",rdp.FondoReserva));
        this.txt_DecimoTercero.setText(String.format("%.2f",rdp.DecimoTercero));
        this.txt_DecimoCuarto.setText(String.format("%.2f",rdp.DecimoCuarto));
        this.txt_FondosReserva.setText(String.format("%.2f",rdp.impuestoRenta));
        this.txt_TotalIngresos.setText(String.format("%.2f",rdp.totalIngreso));
        this.txt_TotalDescuentos.setText(String.format("%.2f",rdp.totalDescuento));
        this.txt_ValorRecibir.setText(String.format("%.2f",rdp.totalRecibir));
        
        rdp.debugAtributos();
    }//GEN-LAST:event_btnCalcularRolActionPerformed

    private void txbCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txbCedulaKeyTyped
        // TODO add your handling code here:
        limpiador.limitarLargo(evt, txbCedula, 10);
    }//GEN-LAST:event_txbCedulaKeyTyped

    private void txtCedulaBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaBusquedaKeyTyped
        // TODO add your handling code here:
        limpiador.limitarLargo(evt, txtCedulaBusqueda, 10);

    }//GEN-LAST:event_txtCedulaBusquedaKeyTyped

    private void txtHorasExtras50KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHorasExtras50KeyTyped
        // TODO add your handling code here:
        limpiador.limitarLargo(evt, txtHorasExtras50, 2);
    }//GEN-LAST:event_txtHorasExtras50KeyTyped

    private void txtHorasExtras100KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHorasExtras100KeyTyped
        // TODO add your handling code here:
        limpiador.limitarLargo(evt, txtHorasExtras100, 2);
    }//GEN-LAST:event_txtHorasExtras100KeyTyped

    private void txtComisionesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtComisionesKeyTyped
        // TODO add your handling code here:
        limpiador.limitarLargo(evt, txtComisiones, 7);
    }//GEN-LAST:event_txtComisionesKeyTyped

    private void txtMultasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMultasKeyTyped
        // TODO add your handling code here:
        limpiador.limitarLargo(evt, txtMultas, 7);
    }//GEN-LAST:event_txtMultasKeyTyped

    private void txtAnticiposKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnticiposKeyTyped
        // TODO add your handling code here:
        limpiador.limitarLargo(evt, txtAnticipos, 7);
    }//GEN-LAST:event_txtAnticiposKeyTyped
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane LayeredPane;
    private javax.swing.JButton btnCalcularRol;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCargarDatos;
    private javax.swing.JButton btn_AgregarTrabajador;
    private org.edisoncor.gui.button.ButtonTransluceIcon btn_GenerarRol;
    private org.edisoncor.gui.button.ButtonTransluceIcon btn_RegistroSueldos;
    private org.edisoncor.gui.button.ButtonTransluceIcon btn_RegistroTrabajadores;
    private javax.swing.JButton btn_registrarRol;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbo_Ciudad;
    private javax.swing.JComboBox<String> cbo_Provincia;
    private javax.swing.JComboBox<String> cbo_TipIden;
    private javax.swing.JComboBox<String> cmbMesReporte;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private static javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_GenerarRol;
    private javax.swing.JLabel lbl_RegistroSueldos;
    private javax.swing.JLabel lbl_RegistroTrabajdores;
    private javax.swing.JPanel pnlRegistroTrabajador;
    private javax.swing.JPanel pnlReportes;
    private javax.swing.JRadioButton radDecimoCuarto;
    private javax.swing.JRadioButton radDecimoTercero;
    private javax.swing.JRadioButton radFondosReserva;
    private javax.swing.JRadioButton radIndividual;
    private javax.swing.JRadioButton radTodos;
    private javax.swing.JTable tablaReporte;
    private javax.swing.JTextField txbCedula;
    private javax.swing.JTextField txtAnticipos;
    private javax.swing.JTextField txtCedulaBusqueda;
    private javax.swing.JTextField txtComisiones;
    private javax.swing.JTextField txtHorasExtras100;
    private javax.swing.JTextField txtHorasExtras50;
    private javax.swing.JLabel txtIngreseIdent;
    private javax.swing.JTextField txtMultas;
    private javax.swing.JTextField txt_Apellidos;
    private javax.swing.JTextField txt_DecimoCuarto;
    private javax.swing.JTextField txt_DecimoTercero;
    private javax.swing.JTextField txt_Direccion;
    private javax.swing.JTextField txt_FondosReserva;
    private javax.swing.JTextField txt_Identificacion;
    private javax.swing.JTextField txt_Iess;
    private javax.swing.JTextField txt_ImpuestoRenta;
    private javax.swing.JTextField txt_Nombres;
    private javax.swing.JTextField txt_Sueldo;
    private javax.swing.JTextField txt_Telefono;
    private javax.swing.JTextField txt_TotalDescuentos;
    private javax.swing.JTextField txt_TotalIngresos;
    private javax.swing.JTextField txt_ValorRecibir;
    private javax.swing.JLabel txt_nombreTrabajador;
    private javax.swing.JTextField txt_sueldo;
    // End of variables declaration//GEN-END:variables
}
