/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.ConectorDB;
import Clases.LimpiadorDeEntrada;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fabricio Mero
 */
public class ReporteRol extends javax.swing.JFrame {

    /**
     * Creates new form ReporteRol
     */
    public ReporteRol() {
        initComponents();
        this.setLocationRelativeTo(null); //Centrar pantalla
        radIndividual.setSelected(true);
        tablaReporte.getColumnModel().getColumn(0).setPreferredWidth(200);
        tablaReporte.getColumnModel().getColumn(1).setPreferredWidth(80);
        tablaReporte.getColumnModel().getColumn(2).setPreferredWidth(80);
        tablaReporte.getColumnModel().getColumn(3).setPreferredWidth(80);
        tablaReporte.getColumnModel().getColumn(4).setPreferredWidth(80);
        tablaReporte.getColumnModel().getColumn(5).setPreferredWidth(80);
        tablaReporte.getColumnModel().getColumn(6).setPreferredWidth(80);
        tablaReporte.getColumnModel().getColumn(7).setPreferredWidth(80);
        tablaReporte.getColumnModel().getColumn(8).setPreferredWidth(80);
        tablaReporte.getColumnModel().getColumn(9).setPreferredWidth(80);
        tablaReporte.getColumnModel().getColumn(10).setPreferredWidth(80);
        tablaReporte.getColumnModel().getColumn(11).setPreferredWidth(80);
        tablaReporte.getColumnModel().getColumn(12).setPreferredWidth(80);
        
        
        
    }
    
    LimpiadorDeEntrada limpiador = new LimpiadorDeEntrada(); 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radIndividual = new javax.swing.JRadioButton();
        radTodos = new javax.swing.JRadioButton();
        txbCedula = new javax.swing.JTextField();
        txtIngreseIdent = new javax.swing.JLabel();
        cmbMesReporte = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaReporte = new javax.swing.JTable();
        txtIngreseIdent1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        radIndividual.setText("Individual");
        radIndividual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radIndividualActionPerformed(evt);
            }
        });

        radTodos.setText("Todos");
        radTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radTodosActionPerformed(evt);
            }
        });

        txbCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txbCedulaKeyTyped(evt);
            }
        });

        txtIngreseIdent.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtIngreseIdent.setText("Ingrese identificacion");

        cmbMesReporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel26.setText("Mes");

        jButton2.setText("Consultar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tablaReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Trabajador", "Sueldo", "IESS", "H. Extra 50%", "H. Extra 100%", "Dec. Tercero", "Dec. Cuarto", "Fondos de reserva", "I. Renta", "Comisiones", "Multas", "Anticipos", "Total Ingresos", "Total descuentos", "Valor a recibir"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaReporte.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaReporte);
        if (tablaReporte.getColumnModel().getColumnCount() > 0) {
            tablaReporte.getColumnModel().getColumn(0).setResizable(false);
            tablaReporte.getColumnModel().getColumn(5).setResizable(false);
        }

        txtIngreseIdent1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtIngreseIdent1.setForeground(new java.awt.Color(255, 102, 0));
        txtIngreseIdent1.setText("Reporte de Rol de Pagos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radTodos)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radIndividual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txbCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIngreseIdent))))
                .addGap(55, 578, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbMesReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel26)))
                .addGap(28, 28, 28)
                .addComponent(jButton2)
                .addGap(626, 626, 626))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtIngreseIdent1)
                .addGap(700, 700, 700))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtIngreseIdent1)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIngreseIdent)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radIndividual)
                    .addComponent(txbCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMesReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radIndividualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radIndividualActionPerformed
        radTodos.setSelected(false);
        txtIngreseIdent.setVisible(true);
        txbCedula.setVisible(true);
    }//GEN-LAST:event_radIndividualActionPerformed

    private void radTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radTodosActionPerformed
        radIndividual.setSelected(false);
        txtIngreseIdent.setVisible(false);
        txbCedula.setVisible(false);

    }//GEN-LAST:event_radTodosActionPerformed
    
    private void txbCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txbCedulaKeyTyped
        limpiador.limitarLargo(evt, txbCedula, 10);
    }//GEN-LAST:event_txbCedulaKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
        

        // Limpiamos la tabla.
        DefaultTableModel dtm = (DefaultTableModel) tablaReporte.getModel();
        dtm.setRowCount(0);

        int mes = cmbMesReporte.getSelectedIndex();
        int nFilas;

        if (mes == 0){
            JOptionPane.showMessageDialog(this, "Seleccione un mes");
            return;
        }

        if (radTodos.isSelected()){
            // Para tratar con la DB.
            ConectorDB con = new ConectorDB();

            nFilas = 0;

            //String query = "SELECT * FROM RolDePagosMensual where ";
            String query = "SELECT rdp.*, t.Nombres + ' ' + t.Apellidos as nombre FROM RolDePagosMensual rdp, Trabajador t"
            + " where t.Identificacion = rdp.cedula and " + "Month(rdp.Mes) = " + mes;
            ResultSet rs = null;

            rs = con.consultar(query);

            if (rs == null){
                System.out.println("error al carga de tabla RodDePagos todos");
                return;
            }

            try{
                while(rs.next()){
                    nFilas ++;
                    DefaultTableModel model = (DefaultTableModel) tablaReporte.getModel();
                    model.addRow(new Object[]{rs.getString("nombre"), rs.getDouble("Sueldo"),rs.getDouble("Iess"),
                        rs.getDouble("valorHorasExtra50"), rs.getDouble("valorHorasExtra100"), rs.getDouble("DecimoTercero"),
                        rs.getDouble("DecimoCuarto"),rs.getDouble("valorHorasExtra50"), rs.getDouble("FondosReserva"),
                        rs.getDouble("ImpuestoRenta"), rs.getDouble("Comisiones"), rs.getDouble("Multas"), rs.getDouble("Anticipos"),
                        rs.getDouble("TotalIngresos"), rs.getDouble("TotalDescuento"), rs.getDouble("ValorRecibir")});
            }
        }
        catch( SQLException ex)
        {
            System.out.println("error en ejecutarConsulta");
            return;
        }

        if (nFilas == 0){
            JOptionPane.showMessageDialog(this, "No hay coincidencias");
        }
        }
        else if (radIndividual.isSelected()){
            // Para tratar con la DB.
            ConectorDB con = new ConectorDB();
            
            // Verificamos input.
            if (txbCedula.getText().length() != 10 || !limpiador.ValidarCedula(txbCedula.getText())){
                JOptionPane.showMessageDialog(this, "Ingrese una cédula válida");
                return;
            }

            nFilas = 0;

            String query = "SELECT rdp.*, t.Nombres + ' ' + t.Apellidos as nombre FROM RolDePagosMensual rdp, Trabajador t"
            + " where rdp.cedula= '" + this.txbCedula.getText() + "' and t.Identificacion = '" + this.txbCedula.getText() + "' and "
            + "Month(rdp.Mes) = " + mes;

            ResultSet rs = null;

            rs = con.consultar(query);

            if (rs == null){
                System.out.println("error al carga de tabla RodDePagos individual");
                return;
            }
            
            

            try{
                if(rs.next()){
                    nFilas ++;
                    //JRResultSetDataSource resultsetdatasource = new JRResultSetDataSource(rs);
                    //JasperFillManager.fillReport(in, parameterMap, new JRResultSetDataSource(rs));
                    DefaultTableModel model = (DefaultTableModel) tablaReporte.getModel();
                    model.addRow(new Object[]{rs.getString("nombre"), rs.getDouble("Sueldo"),rs.getDouble("Iess"),
                        rs.getDouble("valorHorasExtra50"), rs.getDouble("valorHorasExtra100"), rs.getDouble("DecimoTercero"),
                        rs.getDouble("DecimoCuarto"), rs.getDouble("FondosReserva"),
                        rs.getDouble("ImpuestoRenta"), rs.getDouble("Comisiones"), rs.getDouble("Multas"), rs.getDouble("Anticipos"),
                        rs.getDouble("TotalIngresos"), rs.getDouble("TotalDescuento"), rs.getDouble("ValorRecibir")});
            }
        }
        catch( SQLException ex)
        {
            System.out.println("error en ejecutarConsulta");
            return;
        }

        if (nFilas == 0){
            JOptionPane.showMessageDialog(this, "No hay coincidencias");
        }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteRol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteRol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteRol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteRol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReporteRol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbMesReporte;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radIndividual;
    private javax.swing.JRadioButton radTodos;
    private javax.swing.JTable tablaReporte;
    private javax.swing.JTextField txbCedula;
    private javax.swing.JLabel txtIngreseIdent;
    private javax.swing.JLabel txtIngreseIdent1;
    // End of variables declaration//GEN-END:variables
}
